version : '3'

services : 
  nginx:
    build: 
      context: .
      dockerfile: ./docker/nginx-dev/Dockerfile
    image: creating_digital/nginx:1.0.0
    volumes: 
      - /srv/phonebook/app/:/var/www/html:/var/www/html
    ports:
      - 80:80
    networks: 
      - appnet
    depends_on:
      - php-fpm
    restart: unless-stopped

  php-fpm:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    image: creating_digital/php-fpm:1.0.0
    volumes: 
      - /srv/phonebook/app/:/var/www/html
    networks: 
      - appnet
    restart: unless-stopped

  mysql-svc:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    image: creating_digital/mysql:1.0.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=root # would never do this on a real server but for sake of brevity
      - MYSQL_DATABASE=db
    ports:
      - 3306:3306
    networks: 
      - appnet
    restart: unless-stopped

volumes:
  mysql_data:

networks: 
  appnet: